.cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee, src/Tag/README.md, src/Tag/__stories__/Tag.stories.js, src/Tag/__tests__/Tag.test.js, src/Tag/__tests__/__snapshots__/Tag.test.js.snap, src/Tag/index.js, src/index.js
create tag component
create tag component
=> feat(Tag): create tag component

src/Popover/__tests__/__snapshots__/Popover.test.js.snap, src/Popover/elements.js, src/Popover/index.js
refactor(popover): component enhancement
- Animation enhancement
- Remove condition in `PopOver` **styled-component** we have a default `props` for that
=> refactor(popover): component enhancement

src/Button/__tests__/Button.test.js, src/Button/__tests__/__snapshots__/Button.test.js.snap
test(Button): code coverage improvement
test(Button): code coverage improvement
=> test(Button): code coverage improvement

src/ToggleButton/__tests__/ToggleButton.test.js, src/ToggleButton/__tests__/__snapshots__/ToggleButton.test.js.snap
test(ToggleButton): improve coverage
test(ToggleButton): improve coverage
=> test(ToggleButton): improve coverage

src/Date/DateRangePicker/index.js, src/Form/Field/index.js, src/Input/NumberInput/index.js, src/KpiBlock/index.js, src/Modal/__tests__/Modal.test.js, src/Modal/__tests__/__snapshots__/Modal.test.js.snap, src/Modal/index.js
test(Modal): improve code coverage
test(Modal): improve code coverage
=> test(Modal): improve code coverage

src/Value/README.md, src/Value/__stories__/Value.stories.js, src/Value/__tests__/Value.test.js, src/Value/__tests__/__snapshots__/Value.test.js.snap, src/Value/index.js, src/index.js
Create value component
Create value component
=> feat(Value): create value component

src/Value/__tests__/Value.test.js, src/Value/__tests__/__snapshots__/Value.test.js.snap
test(value): fix typo
test(value): fix typo
=> test(value): fix typo

src/Modal/__tests__/Modal.test.js, src/Modal/__tests__/__snapshots__/Modal.test.js.snap
test(modal): improve coverage
test(modal): improve coverage
=> test(modal): improve coverage

package.json, src/Date/DateRangePicker/index.js, src/Form/Field/index.js, src/Input/NumberInput/index.js, src/KpiBlock/index.js, src/Table/README.md, src/Table/__stories__/Table.stories.js, src/Table/__tests__/Table.test.js, src/Table/__tests__/__snapshots__/Table.test.js.snap, src/Table/elements.js, src/Table/index.js, src/index.js
Create Table component
Create Table component
=> feat(Table): create Table component

package.json, src/ButtonGroup/README.md, src/ButtonGroup/__stories__/ButtonGroup.stories.js, src/ButtonGroup/__tests__/ButtonGroup.test.js, src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap, src/ButtonGroup/index.js, src/index.js
Create button group component
feat(ButtonGroup): create button group component
=> feat(ButtonGroup): create button group component

.gitignore, package.json
Add a script which can build the app used by our architect ( Rops ) to deploy it online.
=> Add build script for storybook

src/Counter/__tests__/Increment.test.js, src/Counter/__tests__/__snapshots__/Increment.test.js.snap, src/Counter/index.js
Refactor` unit test with react-testing-library instead of Enzyme.
close #255
=> test(Counter): use react-testing-library instead of enzyme

src/Message/__tests__/Message.test.js, src/Message/__tests__/__snapshots__/Message.test.js.snap
Refactor` unit test with react-testing-library instead of Enzyme.
close #264
=> test(message): use react-testing-library instead of enzyme

src/Pin/README.md, src/Pin/__stories__/pin.stories.js, src/Pin/__tests__/Pin.test.js, src/Pin/__tests__/__snapshots__/Pin.test.js.snap, src/Pin/index.js
=> feat(pin): add new pin component

src/KpiBlock/__tests__/KpiBlock.test.js, src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
Refactor`<KpiBlock /> unit test with [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of [Enzyme](https://github.com/airbnb/enzyme/). 
close #261
=> test(KpiBlock): use react-testing-library instead of enzyme

src/index.js
fix(Pin): export Pin component
=> fix(Pin): export Pin component

src/Modal/README.md, src/Modal/__stories__/Modal.stories.js, src/Modal/__tests__/Modal.test.js, src/Modal/elements.js, src/Modal/index.js, src/helpers/__tests__/colors.test.js, src/helpers/colors.js
=> Add custom padding to Modal component

src/Modal/__tests__/Modal.test.js, src/Modal/__tests__/__snapshots__/Modal.test.js.snap
=> test(Modal): fix modal test

src/Theme/README.md, src/Theme/__stories__/palette.stories.js
Create a story which lists all color palette
=> feat(Theme): create a story which lists all color palette

src/Button/__tests__/Button.test.js, src/Button/__tests__/__snapshots__/Button.test.js.snap, src/Button/__tests__/__snapshots__/helpers.test.js.snap, src/Button/elements.js, src/Button/helpers.js, src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap, src/Counter/__tests__/__snapshots__/Increment.test.js.snap, src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap, src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap, src/Form/__tests__/__snapshots__/Form.test.js.snap, src/KpiChart/__tests__/__snapshots__/KpiChart.test.js.snap
Fix button size to suit our style guide
=>  fix(Button): fix button size

internal/tools/release.sh
Fix URL to changelog file
Fix URL to changelog file
=> fix(tools): fix wrong url to changelog

src/Button/helpers.js, src/Tooltip/README.md, src/Tooltip/__stories__/Tooltip.stories.js, src/Tooltip/__tests__/Tooltip.test.js, src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap, src/Tooltip/elements.js, src/Tooltip/helpers.js, src/Tooltip/index.js
Quick change which permit to overwrite Tooltip's style.
=> feat(Tooltip): Add a props to switch tooltip's appearance

src/Select/Option/index.js, src/Select/README.md, src/Select/__stories__/Select.stories.js, src/Select/__tests__/Select.test.js, src/Select/index.js
Update Select component to render more things than just strings in the options.
Update Select to render the country selector for Catalog https://projects.invisionapp.com/d/main#/console/16028670/341551522/preview
=> feat(Select): add possibility to render other than string in option

src/Select/README.md, src/Select/__stories__/Select.stories.js, src/Select/__tests__/Select.test.js, src/Select/__tests__/__snapshots__/Select.test.js.snap, src/Select/index.js
Add custom width to Select component.
=> fix(Select): add width prop to Select component

src/Form/Field/index.js, src/Form/__tests__/__snapshots__/Form.test.js.snap
Fix className prop in Form/Field component.
=> fix(Form/Field): fix className prop

src/Form/Field/elements.js, src/Form/Field/index.js, src/Form/Group/elements.js, src/Form/__tests__/__snapshots__/Form.test.js.snap
After the discussion I've got with @arthurmonnet, he told me the `<Form.Field/>` and `<Form.Group/>` going to have the same size in each form. In the futur that size gonna have variation like small, default and big but for now he have no idea so just one size is set.
=>  feat(Form): Add new margin according to form design

src/Form/Field/elements.js, src/Form/Group/elements.js, src/Form/__stories__/Form.stories.js, src/Form/__tests__/__snapshots__/Form.test.js.snap, src/Select/__tests__/__snapshots__/Select.test.js.snap, src/Select/elements.js, src/Select/index.js
Fix style for multiple cases of Form (row, inline labels). Add a fixed height for Select component.
=> fix(*): fix Form and Select styles

internal/jest/index.js, src/Date/DatePicker/__tests__/DatePicker.test.js, src/Date/DatePicker/index.js, src/Input/DatePickerInput/README.md, src/Input/DatePickerInput/__stories__/DatePickerInput.stories.js, src/Input/DatePickerInput/__tests__/DatePickerInput.test.js, src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap, src/Input/DatePickerInput/elements.js, src/Input/DatePickerInput/index.js, src/Input/index.js, src/index.js
Fix Date Picker component display.
Add a new component DatePickerInput which provides an input displaying a date picker.
Date Picker now displays the month of the current date when controlled.
DatePickerInput displays a Date Picker that can be updated through a Text Input with minimal validation (a valid Luxon DateTime).
=> feat(Date): add DatePickerInput component

src/Variation/README.md, src/Variation/__stories__/Variation.stories.js, src/Variation/__tests__/Variation.test.js, src/Variation/__tests__/__snapshots__/Variation.test.js.snap, src/Variation/index.js, src/index.js
=> feat(Variation): create Variation component

src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap, src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap, src/Date/Weeks/__tests__/__snapshots__/Week.test.js.snap, src/Date/Weeks/index.js, src/Input/DatePickerInput/__tests__/DatePickerInput.test.js, src/Input/DatePickerInput/index.js
Fixed error state update of DatePickerInput
Made date limits included in authorized date range
Error state is now properly updated according to the parent if it wants to update the prop to force the error state of DatePickerInput.
The range of authorized dates if minDate and maxDate are provided has also been fixed.
=> fix(Date/*): update error state in DatePickerInput and date range limits in Weeks

src/KpiChart/elements.js, src/KpiChart/index.js
Update KpiChart title style.
I don't know yet how we will update this component since the title will be in facts multiple tabs the user can interact with. This is a quick fix that won't handle that future case, but any ideas are welcome :)
>  [TTB-1340](https://tillersystems.atlassian.net/browse/TTB-1340)
=> fix(KpiChart): update Title style

src/Modal/elements.js
Fix a bug that makes the modal not center well in safari
=> fix(Modal): Fix a bug that makes the modal not center well in safari

.circleci/config.yml
Just fix nodejs image version for circleci
=> chore(ci): Fix circleci nodejs image version to 11.10.1

src/CheckBox/__stories__/CheckBox.stories.js, src/CheckBox/__tests__/CheckBox.test.js, src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap, src/CheckBox/elements.js, src/CheckBox/index.js, src/DatePicker/__tests__/DatePicker.test.js, src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap, src/Form/__tests__/__snapshots__/Form.test.js.snap, src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap, src/Input/NumberInput/__tests__/NumberInput.test.js, src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap, src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap, src/Input/TextInput/index.js
Remove buggy shadow on mobile.
I refactored a little the component and adding a shadow in checkbox when focused (a11y)
from: 
to:
> [RAN-12](https://tillersystems.atlassian.net/browse/RAN-12)
=> fix(Checkbox): remove shadow on mobile device

src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap, src/KpiBlock/index.js
Update style for when variation is not provided to KpiBlock component.
=> fix(KpiBlock): improve UI when there is no variation to display

src/TabSwitcher/README.md, src/TabSwitcher/__stories__/TabSwitcher.stories.js, src/TabSwitcher/__tests__/TabSwitcher.test.js, src/TabSwitcher/index.js
Move TabSwitcher from class to function
React hooks are awesome!
=> refactor(TabSwitcher): move TabSwitcher from class to function

src/TabSwitcher/Tab/elements.js, src/TabSwitcher/Tabs/elements.js, src/TabSwitcher/__tests__/TabSwitcher.test.js
Another update for Tabs, sorry 🙏 just CSS update.
=> fix(TabSwitcher): update CSS

src/Form/__tests__/__snapshots__/Form.test.js.snap, src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap, src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap, src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap, src/Input/TextInput/elements.js
I put the font-size on the placeholder instead of the input 🤦‍♀️
=> fix(Input): put font-size at 16px

src/Select/__stories__/Select.stories.js, src/Select/__tests__/Select.test.js, src/Select/index.js
Fix value update from parent to Select component.
Update resetValue in Select state and only `resetValue === true`  will reset the value to null.
=> fix(Select): update value passed by parent and update resetValue

internal/jest/index.js, internal/jest/utils.js, package.json, src/RadioGroup/__tests__/RadioGroup.test.js, src/RadioGroup/__tests__/__snapshots__/RadioGroup.test.js.snap, yarn.lock
=> chore: Remove enzyme test library

.storybook/config.js, .storybook/styles.js, package.json, src/Avatar/__stories__/Avatar.stories.js, src/Avatar/index.js, src/Button/__tests__/__snapshots__/Button.test.js.snap, src/Dropdown/index.js, src/Input/DatePickerInput/index.js, src/Input/TextInput/index.js, src/Popover/index.js, yarn.lock
- update styled-component & react-pose to the latest version
- fix deprecation warning
=> chore(deps): update styled-component & react-pose to the latest version

package.json
update peerDependencies to the latest version to avoid warning when installing stardust
=> chore(deps): update "peerDependencies

src/Popover/index.js
So hopefully I won't need to add another fix for that bug...
=> fix(Popover): retrieve isOpen to trigger rerender

src/Dropdown/elements.js, src/Select/elements.js
=> fix: remove border and radius of menu that are now in the parent

src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap, src/Select/__tests__/__snapshots__/Select.test.js.snap, src/Select/elements.js
As seen with Arthur there was a mistake about the color on Select.
=> fix(Select): update color of text

src/Card/Body/index.js, src/Card/Footer/index.js, src/Card/Header/index.js, src/Card/README.md, src/Card/__stories__/Card.stories.js, src/Card/__test__/Card.test.js, src/Card/__test__/__snapshots__/Card.test.js.snap, src/Card/index.js, src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
The ticket [BP-266](https://tillersystems.atlassian.net/jira/software/projects/BP/boards/57/backlog?selectedIssue=BP-266) ask us to create a pie chart for Sonar dashboard. The pie chart is display in a card which will be generic and reused in all Sonar page. As @sun-tea  [comment](https://github.com/tillersystems/tiller-sonar/pull/1114#pullrequestreview-269118747) says, we should put that card in Stardust for reusability.
=> feat(Card): Add Card component to storybook

src/index.js
Hot fix which add an Card component export.
=> fix(Card): Add export to Card

src/CheckBox/README.md, src/CheckBox/__stories__/CheckBox.stories.js, src/CheckBox/__tests__/CheckBox.test.js, src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap, src/CheckBox/elements.js, src/CheckBox/index.js
The uncontrolled & controlled state doesn't work properly. We decided to refacto the CheckBox component. 
>  [BP-360](https://tillersystems.atlassian.net/browse/BP-360)
=> refactor(CheckBox): Rework the uncontrolled & controlled state

src/ToggleButton/README.md, src/ToggleButton/__stories__/ToggleButton.stories.js, src/ToggleButton/__tests__/ToggleButton.test.js, src/ToggleButton/__tests__/__snapshots__/ToggleButton.test.js.snap, src/ToggleButton/elements.js, src/ToggleButton/index.js
The uncontrolled & controlled state doesn't work properly. We decided to refactor the `ToggleButton` component.
>  [BP-363](https://tillersystems.atlassian.net/browse/BP-363)
=> refactor(ToggleButton): Rework the uncontrolled & controlled state

src/Counter/README.md, src/Counter/__stories__/Counter.stories.js, src/Counter/__tests__/Increment.test.js, src/Counter/index.js
The uncontrolled & controlled state doesn't work properly. We decided to refactor the Counter component.
>  [BP-362](https://tillersystems.atlassian.net/browse/BP-362)
=> refactor(Counter): Rework the uncontrolled & controlled state

package.json, src/ButtonGroup/__tests__/ButtonGroup.test.js, src/Notification/__tests__/provider.test.js, yarn.lock
update react to the latest version
=> chore(deps): update react to the latest version

src/CheckBox/index.js, src/Dropdown/__stories__/Dropdown.stories.js, src/Dropdown/index.js, src/Select/elements.js, src/Select/index.js
Just some adjustments of style
=> fix: update style of Checkbox, Dropdown, Select

src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap, src/Dropdown/elements.js, src/Select/__tests__/__snapshots__/Select.test.js.snap, src/Select/elements.js, src/Tag/__tests__/__snapshots__/Tag.test.js.snap, src/Tag/index.js
=> fix: update css of some Dropdown, Select and Tag

src/Table/elements.js
Sticky footer was broken on safari/ios
>  part of [BP-434 feedback from Arthur](https://tillersystems.atlassian.net/browse/BP-434?focusedCommentId=14433&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14433)
=> fix(Table): fix sticky for safari/ios

src/Table/elements.js
Here we fix some issue about table component. 
>  [BP-434](https://tillersystems.atlassian.net/browse/BP-434?focusedCommentId=14433&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14433)
=> fix(Table): Fix first header cell height

src/Input/Status/__tests__/__snapshots__/status.test.js.snap, src/Input/Status/index.js, src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
fix input error  status alignment
=> fix(Input): fix input error  status alignment

src/Table/elements.js, src/Table/index.js
Put normal font weight on children rows and add `cursor: pointer` on whole row if it has children
=> fix(Table): update css

src/Table/elements.js, src/Table/index.js
We fix the mobile version (columns issue) and the scroll issue.
>  [BP-434](https://tillersystems.atlassian.net/browse/BP-434)
=> fix(Table): mobile version + scroll issue

src/List/index.js
=> fix(List): add className prop for styled-components

src/helpers/formatting.js
=> fix(helpers): divide by 100 all money amounts

src/Table/index.js
Re-render table shadows when adding/removing column.
> [BP-516](https://tillersystems.atlassian.net/browse/BP-516)
yarn link and manual test in local
=> fix(Table): handle shadow rendering when adding/removing columns

src/List/Item/elements.js, src/List/index.js, src/helpers/formatting.js, src/helpers/index.js, src/index.js
=> fix: update formatting helpers and List component

src/Table/TableBody.js, src/Table/TableFooter.js, src/Table/TableHeader.js, src/Table/__stories__/Table.stories.js, src/Table/elements.js, src/Table/index.js
- Fix a bug when deleting a column used to sort the table 
- Splitting the `Table` component to improve performance and avoid unnecessary re-renderings
- Ability to add/remove columns in storybook for the `Table` component
Unit tests + manual tests in Sonar (yarn link)
=> refacto(Table): split component to improve perfs + fix sort on add/remove columns

src/BreadCrumb/Item/index.js, src/BreadCrumb/README.md, src/BreadCrumb/__stories__/BreadCrumb.stories.js, src/BreadCrumb/__tests__/BreadCrumb.test.js, src/BreadCrumb/index.js, src/index.js
We want to show the user history path displayed in breadcrumb
>  [BP-601](https://tillersystems.atlassian.net/browse/BP-601)
=> feat(BreadCrumb): Add component to Stardust

src/Navigation/README.md, src/Navigation/__stories__/Navigation.stories.js, src/Navigation/__tests__/Navigation.test.js, src/Navigation/elements.js, src/Navigation/index.js
Add Navigation component to the project
>  [BP-661](https://tillersystems.atlassian.net/browse/BP-661)
=> feat(Navigation): Add component Navigation to project

src/Select/index.js
Pass all popovers props through select for flexibility
=> fix(Select): pass all Popover props

src/Navigation/elements.js, src/Select/__tests__/__snapshots__/Select.test.js.snap, src/Select/elements.js, src/index.js
* Export Navigation component to use it...
* Add a class active (for NavLink for instance) to handle active state
* Reduce Select padding to avoid premature ellipsis.
[BP-661](https://tillersystems.atlassian.net/browse/BP-661)
Snapshots updated
=> fix: Navigation export, Navigation active class name, Select style

src/Navigation/index.js
=> fix(Navigation): add possibility to custom style

src/CheckBox/Bullet.js, src/CheckBox/__tests__/CheckBox.test.js, src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap, src/CheckBox/elements.js, src/CheckBox/index.js, src/OptionsList/Options/CheckboxOption.js, src/OptionsList/Options/RadioOption.js, src/OptionsList/Options/SimpleOption.js, src/OptionsList/SearchBar.js, src/OptionsList/__stories__/OptionsList.stories.js, src/OptionsList/__tests__/OptionsList.test.js, src/OptionsList/elements.js, src/OptionsList/helpers.js, src/OptionsList/index.js, src/RadioButton/Bullet.js, src/RadioButton/__stories__/RadioButton.stories.js, src/RadioButton/__tests__/__snapshots__/RadioButton.test.js.snap, src/RadioButton/elements.js, src/RadioButton/index.js, src/RadioGroup/__tests__/__snapshots__/RadioGroup.test.js.snap
Improve performances of OptionsList:
* Rewrite OptionsLIst as a PureComponent
* use a memo util for all Option Component
* Rewrite RadioButton and CheckBox to match same pattern
* Expose a Styled Bullet for Radio and CheckBox
Tests updated
=> fix(OptionsList): rewrite Radio, CheckBox + memo + PureComponent
