tillersystems/Stardust

- src/Logo/__tests__/Logo.test.js
Refactor unit test with [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of [Enzyme](https://github.com/airbnb/enzyme/).
> test(Logo) use react-testing-library instead of enzyme

- src/Tag/__tests__/Tag.test.js
- src/Tag/__tests__/__snapshots__/Tag.test.js.snap
- src/Tag/index.js
Refactor`<Tag /> unit test with [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of [Enzyme](https://github.com/airbnb/enzyme/). 
close #271
> test(Tag): use react-testing-library instead of enzyme

- src/Button/index.js
- src/ButtonGroup/index.js
- src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
- src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
- src/Form/__tests__/__snapshots__/Form.test.js.snap
- src/KpiChart/__tests__/__snapshots__/KpiChart.test.js.snap
In `<ButtonGroup />` we  check `child.type.displayName` instead of just `child.displayName` beacause od styled-components
>  refactor(ButtonGroup): check child.type.displayName instead of child.displayName

- src/ToggleButton/__tests__/ToggleButton.test.js
- src/ToggleButton/__tests__/__snapshots__/ToggleButton.test.js.snap
- src/ToggleButton/index.js
Refactor`<ToggleButton /> unit test with [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of [Enzyme](https://github.com/airbnb/enzyme/). 
close #272
> test(ToggleButton): use react-testing-library instead of enzyme

- src/Loader/__tests__/Loader.test.js
- src/Loader/__tests__/__snapshots__/Loader.test.js.snap
- src/Loader/index.js
Refactor`<Loader /> unit test with [react-testing-library](https://github.com/kentcdodds/react-testing-library) instead of [Enzyme](https://github.com/airbnb/enzyme/). 
close #263
> test(Loader): use react-testing-library instead of enzyme

- src/Tooltip/__tests__/Tooltip.test.js
- src/Tooltip/elements.js
- src/Tooltip/helpers.js
@leopoldhoudin noticed there missing a border on the pseudo-element `::before`. So I open this PR to fix that issue.
> [leopoldhoudin comment](https://github.com/tillersystems/tiller-sonar/pull/435#issuecomment-457522507)
> fix(Tooltip): Add a border to the pseudo-element ::before

- src/Form/__tests__/__snapshots__/Form.test.js.snap
- src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
- src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
- src/Input/TextInput/__stories__/TextInput.stories.js
- src/Input/TextInput/__tests__/TextInput.test.js
- src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
- src/Input/TextInput/elements.js
- src/Input/TextInput/index.js
Fix style for custom props on InputText.
> fix(Input/InputText): allow custom styles to override the style on focused input

- package.json
- src/Form/__tests__/__snapshots__/Form.test.js.snap
- src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
- src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
- src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
- src/Input/TextInput/elements.js
- yarn.lock
Use placeholder pseudo-element instead of deprecated method from polished lib.
Polished dependency [deprecated](https://github.com/styled-components/polished/commit/8792e1ffefecb55bc8fad393cb9111477f2d7f12) its `placeholder()` method, so we need to remove it from our lib.
Stardust is broken because of that in captain-client (weirdly it broke on update of polished dependency in captain-client, I would have thought that inner dependency in Stardust would not be impacted?). Either way this PR is fixing it.
> fix(Input): fix placeholder style

- package.json
- src/DatePicker/Header/__tests__/__snapshots__/Header.test.js.snap
- src/DatePicker/Header/index.js
- src/DatePicker/Weeks/index.js
- src/DatePicker/__stories__/DatePicker.stories.js
- src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
- src/DatePicker/__tests__/__snapshots__/helpers.test.js.snap
- src/DatePicker/__tests__/helpers.test.js
- src/DatePicker/helpers.js
- src/DatePicker/index.js
- src/Input/DatePickerInput/__tests__/DatePickerInput.test.js
- yarn.lock
Fix a bug who `<DatePicker />` did not allow interval (Luxon.Interval) in defaultValue
> fix(DatePicker): allow interval in defaultValue

- src/Modal/elements.js
- src/Modal/index.js
The size of the modal needed to be specified without the modal resizing by itself according to the content. If translations values change, you need to update the height/width of the component, which is cumbersome. That PR aims to fix that.
The mobile version of the modal is also updated to fit design ([Sonar example of the datepicker](https://app.zeplin.io/project/5c08e7dab171cd2fd787d7d6/screen/5ca2107fb4da6a05e1c042e6))
> fix(Modal): fix size and mobile version of the component

- src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
- src/Loader/__tests__/__snapshots__/Loader.test.js.snap
- src/Loader/index.js
Fix loader size for Firefox
The loader uses a svg and rem are not supported on Firefox 🦊 So instead we use pixels.
> fix(Loader): use px instead of rem for Firefox support

- src/KpiChart/__stories__/KpiChart.stories.js
- src/KpiChart/__tests__/KpiChart.test.js
- src/KpiChart/elements.js
- src/KpiChart/index.js
Add design for KpiChart component on mobile devices
Added a prop `isCompacted` to toggle the mobile version of the KpiChart component.
CSS values are based on [Sonar design for Bar Chart](https://app.zeplin.io/project/5c08e7dab171cd2fd787d7d6/screen/5c9cd3fc66d66477528d2c6a)
> fix(KpiChart): add possible design for mobile devices

- src/Modal/elements.js
Add z-index to overlay of modal
This is because I stumbled upon this: 
This may not be the best solution but as the overlay of the modal is supposed to cover up the whole page except modal, but that some elements may also have a z-index, this is the quickest solution to implement to me.
> fix(Modal): add z-index to overlay to avoid elements overlapping it

- src/TabSwitcher/Pane/index.js
- src/TabSwitcher/Panes/elements.js
- src/TabSwitcher/Panes/index.js
- src/TabSwitcher/README.md
- src/TabSwitcher/Tab/elements.js
- src/TabSwitcher/Tab/index.js
- src/TabSwitcher/Tabs/elements.js
- src/TabSwitcher/Tabs/index.js
- src/TabSwitcher/__stories__/TabSwitcher.stories.js
- src/TabSwitcher/__tests__/TabSwitcher.test.js
- src/TabSwitcher/index.js
- src/index.js
Add new TabSwitcher component.
The TabSwitcher can hold content provided on instanciation and has a mobile version handled by the prop `isCompacted`. The component has been created following the compound components pattern. The tabs will need to have its style customized if they are elsewhere than at the top of the panes in order to fit design. 
In the future, animation may be nice to add to animate the blue underline of the selected tab (but for now, each Tab is a separate component so it may need to change).
cf design: [desktop](https://app.zeplin.io/project/5c08e7dab171cd2fd787d7d6/screen/5c505a64ef01a50342e6aaf7) and [mobile](https://app.zeplin.io/project/5c08e7dab171cd2fd787d7d6/screen/5ca5fd0374b8e63e5e5bc9dd)
> feat(TabSwitcher): add new TabSwitcher component

- src/TabSwitcher/Pane/elements.js
- src/TabSwitcher/Pane/index.js
Forgot to add some style to properly display content in a pane.
> fix(TabSwitcher): wrap pane in styled component

- src/Dropdown/elements.js
Add z-index to Menu of Dropdown.
Fix to avoid this: 
At first I wrapped the Dropdown in Sonar but with a Modal this is problematic:
This fix is not perfect since we use z-index without checking how it would behave with other elements but this is a quick fix (use a Portal?)
> fix(Dropdown): add z-index to menu

- src/Form/__tests__/__snapshots__/Form.test.js.snap
- src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
- src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
- src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
- src/Input/TextInput/elements.js
Put 16px font-size in inputs for all browsers instead of trying to target only Safari (`@supports` is not supported by jsdom so our tests are failing).
> fix(input): remove non handled @supports in jsdom and put 16px font-size

- src/TabSwitcher/index.js
If there is a null child, the component breaks as child does not have a type.
> fix(TabSwitcher): add guard for null children

- src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
- src/Tooltip/index.js
Replace `inline-block` by` inline-flex` to fix the align issue with another element.
> fix(Tooltip): replace inline-block by inline-flex

- src/Form/__tests__/__snapshots__/Form.test.js.snap
- src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
- src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
- src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
- src/Input/TextInput/elements.js
Replace **margin** by **padding** inside the input.
Before:
After: 
>
> fix(TextInput): replace margin by padding inside input

- src/Button/__tests__/__snapshots__/helpers.test.js.snap
- src/Button/helpers.js
- src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
- src/Counter/__tests__/__snapshots__/Increment.test.js.snap
- src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
- src/Dropdown/elements.js
- src/Input/Label/index.js
- src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
- src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
- src/KpiChart/Body/__tests__/__snapshots__/Body.test.js.snap
- src/KpiChart/Body/index.js
- src/KpiChart/__stories__/KpiChart.stories.js
- src/KpiChart/__tests__/KpiChart.test.js
- src/RadioButton/__tests__/__snapshots__/RadioButton.test.js.snap
- src/RadioButton/elements.js
- src/RadioGroup/__tests__/__snapshots__/RadioGroup.test.js.snap
- src/Table/elements.js
- src/Theme/palette.js
Update grey colors.
Add height prop to KpiChart.Body
mysticGrey value has been adjusted cf design on Zeplin (typo on visual).
I updated the components using this color by a lighter grey.
I also added the possibility to set a height to the body of KpiChart.
> fix: update color and KpiChart height

- src/TabSwitcher/Panes/index.js
Fix bug in TabSwitcher display for single pane case.
The pane display is based on the index of the children, if there is only one child in Panes, the children is an object so it does not display properly.
> fix(TabSwitcher): display single Pane when there is only one

- src/TabSwitcher/index.js
We need to check for child `diplayName` to avoid error when we use a styled component as child
> fix(TabSwitcher): check for child displayName

- src/TabSwitcher/index.js
We forgot to check if child is not null in case of conditional rendering (which we do in mobile in Sonar)
> fix(TabSwitcher): check that child is not null

- src/Table/index.js
Maybe we should update the Icon component directly?
> fix(Table): specify pix instead of rm for Firefox support

- src/TabSwitcher/Pane/elements.js
- src/TabSwitcher/Pane/index.js
- src/TabSwitcher/Panes/elements.js
- src/TabSwitcher/Panes/index.js
- src/TabSwitcher/README.md
- src/TabSwitcher/Tab/elements.js
- src/TabSwitcher/Tab/index.js
- src/TabSwitcher/Tabs/elements.js
- src/TabSwitcher/Tabs/index.js
- src/TabSwitcher/__stories__/TabSwitcher.stories.js
- src/TabSwitcher/__tests__/TabSwitcher.test.js
- src/TabSwitcher/index.js
Completely  refactor of `TabSwicther` component: 
- use react context instead of react children map to to prevent redeclared`displayName`
- make the tab more accessible
> feat(TabSwicther): use context instead of react children map

- .circleci/config.yml
- package.json
- CircleCI workflow enhancement
- Change `eslint` pre-commit command to `src`
Adding `deploy` step on master pushes for build and deploy Storybook in production
> chore(circleci): Add Storybook generation and deploy on master pushes

- src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
- src/CheckBox/index.js
- src/Input/Status/__tests__/__snapshots__/status.test.js.snap
- src/Input/Status/index.js
- src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
Replace rem by px for svg width and height to avoid warning on Firefox and Safari which do not support rem.
> fix: replace rem by px for Safari and Firefox support

- src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
- src/CheckBox/elements.js
> fix(CheckBox): avoid width of checkbox being less than the width specified

- src/Table/README.md
- src/Table/__stories__/Table.stories.js
- src/Table/__tests__/Table.test.js
- src/Table/index.js
Actually field of the Table component could be hydrated by a single value. If an object was passed only one value could be displayed or no one. This pr add a new support for object in our Table component.
> feat(Table): Add object support to hydrate row field

- src/Dropdown/elements.js
- src/Dropdown/index.js
We need to move the `<Dropdown />` component into a portal. I use the `<Portal>` component provided by the `react-portal` library to render the portal. The portal appear at the bottom of the body and it positioned according to the input.
>  [BP-52](https://tillersystems.atlassian.net/browse/BP-52)
> feat(Dropdown): Add portal to Dropdown component

- src/RadioButton/index.js
- src/RadioGroup/__stories__/RadioGroup.stories.js
- src/RadioGroup/__tests__/RadioGroup.test.js
- src/RadioGroup/index.js
There wasn't any callback to let the parent know of the selected value on update so this PR just adds it.
> fix(RadioGroup): add callback on value update

- src/Dropdown/index.js
When trying to use the Dropdown elsewhere, I stumbled upon an error on the FilteredItems because `children,.toLowerCase()` did not exist. As we don't need the FilteredItems when the component is not searchable, I just put an empty array.
> fix(Dropdown): put empty array to filtered items when searchable is false

- .storybook/.babelrc
Since we update corjs to 3.0 we have a problem to build storybook.
To avoid this error we need to explicity add wich version of corejs we use in the storybook `.babelrc`
https://github.com/storybookjs/storybook/issues/6204#issuecomment-503480927
> chore(babel): specify corejs number in babelrc

- .babelrc
- .storybook/.babelrc
- src/Button/__tests__/Button.test.js
- src/Button/__tests__/__snapshots__/helpers.test.js.snap
- src/DatePicker/Header/__tests__/__snapshots__/Header.test.js.snap
- src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
- src/Dropdown/README.md
- src/Dropdown/__stories__/Dropdown.stories.js
- src/Dropdown/__tests__/Dropdown.test.js
- src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
- src/Dropdown/elements.js
- src/Dropdown/index.js
- src/Form/__tests__/__snapshots__/Form.test.js.snap
- src/RadioButton/__tests__/__snapshots__/RadioButton.test.js.snap
- src/RadioGroup/__tests__/__snapshots__/RadioGroup.test.js.snap
- src/Select/__tests__/__snapshots__/Select.test.js.snap
When using something else than checkboxes on my dropdown, the padding used inside the component was not right for my use, so the simplest way (may be cumbersome I know) was to let the user implement their own style as a prop `itemCss` to avoid that.
> refactor(Dropdown): remove internal style of padding

- package.json
- src/EventListener/__tests__/EventListener.test.js
- src/EventListener/index.js
- src/Input/DatePickerInput/README.md
- src/Input/DatePickerInput/__tests__/DatePickerInput.test.js
- src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
- src/Input/DatePickerInput/index.js
- src/Popover/README.md
- src/Popover/__stories__/Popover.stories.js
- src/Popover/__tests__/Popover.test.js
- src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- src/Popover/elements.js
- src/Popover/index.js
- src/ScrollBox/elements.js
- src/ScrollBox/index.js
- src/index.js
- yarn.lock
In order to fix our Select and Dropdown components, it seemed that a way was to use popper.js to help with the positioning. Since we already have a Popover component, I reworked this component to use popper.js and took the opportunity to add more utils like an EventListener component that can be instanciated each time we want to handle outside click.
Warning: if you test the story from the storybook, position of the arrow when you toggle `hasArrow` may not be accurate because it does not seem to update properly, but if you change the `placement` of the popover it should update.
> refactor(Popover): wrap popover with portal and popper.js

- src/Dropdown/README.md
- src/Dropdown/__stories__/Dropdown.stories.js
- src/Dropdown/__tests__/Dropdown.test.js
- src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
- src/Dropdown/elements.js
- src/Dropdown/index.js
- src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
- src/Popover/__stories__/Popover.stories.js
- src/Popover/__tests__/__snapshots__/Popover.test.js.snap
- src/Popover/elements.js
- src/Popover/index.js
- src/Select/README.md
- src/Select/__stories__/Select.stories.js
- src/Select/__tests__/Select.test.js
- src/Select/__tests__/__snapshots__/Select.test.js.snap
- src/Select/elements.js
- src/Select/index.js
Use Popover component to display the Select and the Dropdown to make them overlap everything with their Portal. 
Outside clicks now closes the Select.
There is now a selected style for the selected item of the Select.
⚠️ Custom animation broke the Select so `animationProps` is not useful right now. I will create a followup issue for that.
> refactor: use Popover to wrap Select and Dropdown components

- internal/jest/index.js
Mock `document.createRange` in test to avoid error, document.createRange is not available in JSDOM
> test: mock document.createRange

- src/Dropdown/index.js
- src/Popover/index.js
- src/Select/index.js
By using the components in Sonar I stumbled upon some problems.
Having nested Portaled components did this:
Plus, having the displayMenu uncontrolled on the Dropdown was triggering unwanted behaviour so now passing the prop `displayMenu` makes it controllable by the parent.
Now:
> fix(Popover): make Portal optional, adjust style, raise refs to parents

- src/RadioButton/index.js
- src/RadioGroup/index.js
Just adding className prop of styled components to allow styled-components to customize style.
> fix(Radios): add className to custom with styled-components

- src/Dropdown/elements.js
- src/Dropdown/index.js
- src/Popover/index.js
- src/Select/elements.js
Small adjustments, when clicking on an svg element, the callback was not being triggered because of the type check. Also I put back the Menu on Dropdown and removed the gradient as per request of Arthur.
> fix: update outside click trigger on Popover and update style of Popover and Select

- src/Dropdown/index.js
`displayMenu` did not seem to trigger rerender despite being updated in the internal state, turns out I think it's because the way the variable was being retrieved would not trigger a rerender.
> fix(Dropdown): retrieve both state and props for displayMenu to trigger rerender

- src/Select/index.js
`100%` value was never put on the component since the regex fallback to `auto`
> fix(Select): allow percentage values for width

- .storybook/addons.js
- .storybook/config.js
- .storybook/webpack.config.js
- package.json
- src/Avatar/README.md
- src/Avatar/__stories__/Avatar.stories.js
- src/Avatar/index.js
- src/Button/README.md
- src/Button/__stories__/Button.stories.js
- src/Button/index.js
- src/ButtonGroup/README.md
- src/ButtonGroup/__stories__/ButtonGroup.stories.js
- src/ButtonGroup/index.js
- src/CheckBox/README.md
- src/CheckBox/__stories__/CheckBox.stories.js
- src/CheckBox/index.js
- src/Counter/README.md
- src/Counter/__stories__/Counter.stories.js
- src/Counter/index.js
- src/DatePicker/README.md
- src/DatePicker/__stories__/DatePicker.stories.js
- src/DatePicker/index.js
- src/Dropdown/README.md
- src/Dropdown/__stories__/Dropdown.stories.js
- src/Dropdown/index.js
- src/ScrollBox/elements.js
- src/Wrapper/index.js
- yarn.lock
First part of the ticket about doc rework.
In the end there are not much changes, as Storybook may be customizable with addons, but still something wired to work a certain way.
So I tried using addon-info, but with the readme addon there are some [problems](https://github.com/storybookjs/storybook/issues/6147) (also [here](https://github.com/tuchk4/storybook-readme/issues/136)) so this is still not used.
Automatic prop tables creation by the addon does not work if component is exported with as styled-component or an HOC so this is why prop tables are still hardcoded in the README.
>  [[Stardust] Rework doc template and apply it on all components](https://tillersystems.atlassian.net/browse/BP-314)
> refactor(doc): update docs and stories from storybook

- src/Card/__test__/__snapshots__/Card.test.js.snap
- src/Card/index.js
As a chart can be displayed inside a card, an overflowing Tooltip would be hidden if used as is.
> fix(Card): makes overflowing content visible

- src/Notification/Container.js
- src/Notification/NotificationsList.js
- src/Notification/README.md
- src/Notification/__stories__/Notifications.stories.js
- src/Notification/__tests__/__snapshots__/helpers.test.js.snap
- src/Notification/__tests__/__snapshots__/reducer.test.js.snap
- src/Notification/__tests__/helpers.test.js
- src/Notification/__tests__/provider.test.js
- src/Notification/__tests__/reducer.test.js
- src/Notification/elements.js
- src/Notification/helpers.js
- src/Notification/provider.js
- src/Notification/reducer.js
Change notifications provider to display multiple notifications.
I modified the component so that it can display multiple notifications. They are now recorded in an array and keep their autoDismiss and pauseOnHover functionality. The provider's signature has evolved so that a notification can be dismissed through its key.
dismissNotification has been modified to accept a key parameter :
```javascript
dismissNotification(key)
```
The notifcation can be manually closed by calling the onClose method injected by the NotificationContainer in the inner component props.
```javascript
const Component = ({ onClose }) => (
<Message description="I'm a notification component" type="success" onClose={onClose} />
);
```
[BP-398](https://tillersystems.atlassian.net/jira/software/projects/BP/boards/57?sel …
> refactor(Notification): Rework of the component to stack notification

- src/Notification/__stories__/Notifications.stories.js
- src/Notification/__tests__/provider.test.js
- src/Notification/provider.js
- src/Notification/reducer.js
Change notification provider to specify a key on `addNotification`. You can dismiss it with the same key.
I modify the component to add a key in `addNotification` options.
```javascript
addNotification(Component, { 
autoDismiss={false}, 
pauseOnHover={false}, 
key: "report-notification"
});
```
You can dismiss the notification using this method :
```javascript
dismissNotification("report-notification");
```
[BP-398](https://tillersystems.atlassian.net/jira/software/projects/BP/boards/57?selectedIssue=BP-398)
Add tests to check the add/dismiss with specific key.
> refactor(Notification): Add key in addNotification options

- package.json
- src/TableVirtualized/README.md
- src/TableVirtualized/__stories__/TableVirtualized.stories.js
- src/TableVirtualized/__tests__/TableVirtualized.test.js
- src/TableVirtualized/elements.js
- src/TableVirtualized/index.js
- src/index.js
- yarn.lock
As we want to add windowing to our Table with react-virtualized, we have to use its components.
To not break the existing Table, for now we are adding a new table comp next to the current one.
First column, header and footer are sticky. Tests are basic since hopefully this Table should merge with the current one. Also this virtualized table will evolve pretty quickly to follow the new features of the sales report we'll have to cover.
>  
> feat(TableVirtualized): use react-virtualized components to create new table

- package.json
- src/TableVirtualized/index.js
- yarn.lock
Since adding `react-virtualized` lib alongside the `dom-helpers` one, when using last version of Stardust on another project (Sonar), `react-virtualized` which also use `dom-helpers` breaks because it does not seem to resolve properly the path to its own `dom-helpers` dep. Don't understand why, so maybe using the same version could be a quick fix.
> chore: downgrade dom-helpers version to match react-virtualized one

- package.json
- src/Modal/Footer/__tests__/Footer.test.js
- src/Modal/animation.js
- src/Modal/elements.js
- src/Modal/index.js
- yarn.lock
This PR is the first of a series. We need to replace [react-pose](https://popmotion.io/pose/) by [framer-motion](https://www.framer.com/api/motion/) since the first one is deprecated.
> refactor(Modal): replace react-pose by framer-motion for the animation

- package.json
- src/Dropdown/__tests__/Dropdown.test.js
- src/Dropdown/animation.js
- src/Dropdown/index.js
- src/Dropdown/utils.js
- src/Popover/__tests__/Popover.test.js
- src/Popover/animation.js
- src/Popover/elements.js
- src/Popover/index.js
- src/Select/__stories__/Select.stories.js
- src/Select/__tests__/Select.test.js
- src/Select/animation.js
- src/Select/index.js
- src/Select/utils.js
- yarn.lock
Replace react-pose by framer-motion for the animation.
This PR also remove react-pose dependecy
> refactor(Popover): replace react-pose by framer-motion for the animation

- src/Table/__stories__/Table.stories.js
- src/Table/__tests__/Table.test.js
- src/Table/elements.js
- src/Table/index.js
Quick fix to change the hoverable element. I change this behaviour to be optional with the props `isHoverable`. Tests done 👍
> fix(Table): Change hover cell to hover row

- src/Select/README.md
- src/Select/__stories__/Select.stories.js
- src/Select/__tests__/Select.test.js
- src/Select/index.js
In order to add the select for type aggregate in sales-analysis page of Sonar, our Select component needs to be able to display more than just the selected value (see design on Zeplin):
>
> feat(Select): add customizable displayed value

- src/Table/README.md
- src/Table/__stories__/Table.stories.js
- src/Table/__tests__/Table.test.js
- src/Table/elements.js
- src/Table/index.js
We want to have extendable row with under-categories in it. Check the [design](https://app.zeplin.io/project/5c08e7dab171cd2fd787d7d6/screen/5d4acbc4e8ad4751ff453b28) for visual overview.
To use the dropdown row you need to add `children` key to `data` prop. `children` structure is the same as `data` one, an object's array.
eg:
```javascript
const data = [
{
...
children: [
{
name: 'children',
price: 9.0,
tax: {
fr: 9.0,
en: 10.0,
},
quantity: 2,
tva: 20,
profit: 4,
discount: 10,
},
...
]
},
...
];
```
>  ([BP-369](https://tillersystems.atlassian.net/browse/BP-369))
> [BP-486](https://tillersystems.atlassian.net/browse/BP-486)
> feat(Table): Add dropdown row

- src/Table/elements.js
- src/Table/index.js
What is already done in that PR :
- changed column width to respect the style guidelines
How that works :
- I check the column's number on the table.
- Add one to the result (because first column take two column width)
- Set column width except first one to `100% / column's number + 1`
- All cell gonna have the same width except the first one which take remaining space (2 columns width)
- First column : To crop text and avoid text overflowing on the other cell I remove `display: flex` attribut which lead to an issue on safari :
icon is not aligned anymore
What is need to be done :
- Fix icon alignement issue
- Check on mobile (Sonar) if the preview implementation works
- Remove freshchat logo 
- Don't fill height when table is not long enough
- Fix/Add tests
- Add shadows to the table
I …
> feat(Table): Change column width to match style guidelines

- src/List/Item/__tests__/Item.test.js
- src/List/Item/elements.js
- src/List/Item/index.js
- src/List/README.md
- src/List/__stories__/List.stories.js
- src/List/__tests__/List.test.js
- src/List/elements.js
- src/List/index.js
- src/helpers/__tests__/formatting.test.js
- src/helpers/formatting.js
- src/helpers/index.js
- src/index.js
[EDITED BY @sun-tea:]
Add list component that will be used in Sonar to replace the current table for "list" view of the "product type" pie chart and the "top products" list. 
I've reused the helpers to format numbers initially created in Sonar, in the long run I think we could remove them from Sonar to only use the ones from Stardust.
As discussed with Arthur, the amounts on the right side of the labels will be pilep up so no need to handle an inlined view.
>  [BP-490](https://tillersystems.atlassian.net/browse/BP-490)
> feat(List): add List component

- src/Table/TableBody.js
- src/Table/__stories__/Table.stories.js
- src/Table/__tests__/Table.test.js
- src/Table/elements.js
- src/Table/index.js
To handle product detail view, the rows need to handle a callback that will allows us to change page. Since selecting a row is not actually used on the Table rn, I've cleaned the code and replace that by what we actually need, i.e. handling click on rows.
>
> refactor(Table): replace selectable by onClick callback

- .circleci/config.yml
- internal/jest/index.js
- src/DatePicker/Day/__tests__/Day.test.js
- src/DatePicker/Day/__tests__/__snapshots__/Day.test.js.snap
- src/DatePicker/Day/elements.js
- src/DatePicker/Day/index.js
- src/DatePicker/Header/__tests__/Header.test.js
- src/DatePicker/Header/__tests__/__snapshots__/Header.test.js.snap
- src/DatePicker/Header/index.js
- src/DatePicker/README.md
- src/DatePicker/Weeks/__tests__/Week.test.js
- src/DatePicker/Weeks/__tests__/__snapshots__/Week.test.js.snap
- src/DatePicker/Weeks/index.js
- src/DatePicker/__stories__/DatePicker.stories.js
- src/DatePicker/__tests__/DatePicker.test.js
- src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
- src/DatePicker/__tests__/helpers.test.js
- src/DatePicker/helpers.js
- src/DatePicker/index.js
Makes multiple months display independant.
Style has been improved for better understanding.
Added prop `displayOnlyInMonth` to allow displaying only days on display month (not the days of the adjacent months).
[BP-508](https://tillersystems.atlassian.net/browse/BP-508)
Storybook & unit tests
rebuild and publish
> feat(DatePicker): independant months display + style lifting

- src/Table/TableBody.js
- src/Table/elements.js
Fix alignment on table between Icon and text in RowHeader.
I try to find a solution for the iPad scroll issue... I don't reproduce the problem all the time. Weird shit...
Basically, Arthur wanted to reduce the size of the table to avoid that the Freshchat button goes over it. He now prefers to wait until we put it in the TopBar.
>  
On Safari iPad (iPad Pro 11 13.3) and Chrome/Safari on desktop
> fix(Table): fix text/icon alignment

- src/CheckBox/index.js
- src/OptionsList/Options/CheckboxOption.js
- src/OptionsList/Options/RadioOption.js
- src/OptionsList/Options/SimpleOption.js
- src/OptionsList/__stories__/OptionsList.stories.js
- src/RadioGroup/index.js
Updated some PropTypes too restrictive.
Use node where string or number or any dom element can be rendered.
Not impacting behaviour
> fix(Checkbox|Radio|OptionsList): allow value as proptype node

- src/Select/Header.js
- src/Select/__stories__/Select.stories.js
- src/Select/__tests__/Select.test.js
- src/Select/index.js
Add a display Value prop to Select (being a function or a node) that can be used to customize the value displayed in Header without overriding the whole header.
Could also enable customizing HeaderComponent without touching the display logic.
Tests and Storybook updated
> feat(Select): reintroduce displayValue props to customize Header

- src/Select/__tests__/__snapshots__/Select.test.js.snap
- src/Select/elements.js
- src/Select/index.js
After reducing padding, text occurs to sometimes "touch" the arrows.
* Increase padding a bit to avoid that behaviour
* Also, give a default values if not provided to avoid TypeError when values is not an array
> fix(Select): multiple fixes

- src/Modal/elements.js
- src/Modal/index.js
Modal container had no z-index, and did not allow passing a className to override container's style, making some absolute/sticky elements to be above the overlay or modal container.
Added a default z-index of 100 (position: fixed  defines the base z-index of all children), and accept className Props if needed.
No changes in tests
> fix(Modal): added className and zIndex to container

- .circleci/config.yml
Trying to fix CD deploy step by adding `apt-get update` process to avoid 404 errors
> fix(CI): Adding apt update to avoid apk break
